### PR TITLE
Add contributing guide

### PR DESCRIPTION
**Pull request by anaulin**
Flesh out basics of contributing to BidWire, including coding conventions, joining Ragtag, etc.

@bradyk and @jillh510 let me know what do you think about the general wording / recommendations in the guide

@klertmen and @jdegrazia : is there anything missing from this that should be there?

### CODE REVIEW

**Comment by klertmen** [comment]
Looks good!

**Comment by jdegrazia** [comment]
@anaulin Looks great to me.

**Comment by jillh510** [comment]
lgtm

**Comment by anaulin** [comment]
Thanks for having a look, y'all!

**Pull request merged**
