### PR TITLE
Add Acknowledgements section to README mentioning Ragtag and @jdegrazia

### PR DESCRIPTION
**Pull request by anaulin**
This PR adds a small blurb mentioning that this project is part of Ragtag, and who are the main collaborators in the project.

@jillh510 and @jdegrazia please have a look and let me know if you're ok with this being submitted into the Bidwire README, or if you have any other suggestions

### CODE REVIEW

**Comment by anaulin** [comment]
@jdegrazia, also let me know if you'd like me to add something about how the idea for this came from HighWire and/or the original developer there (and whatever links to them or the project are appropriate)

**Comment by anaulin** [comment]
@jillh510 gave an LGTM in Slack, so merging this now

**Comment by jdegrazia** [comment]
@anaulin RE: HighWire: No need to mention it. I'll see if Wiley wants us to add him to the Acknowledgements, but my guess is that he won't.

**Comment by jdegrazia** [comment]
@anaulin Wiley says no need to acknowledge him.

**Pull request merged**
